# 是否让任务卷轴只保留一天 ( 每日任务卷轴 )
Delete_every_other_day : true

#是否开启音效
sound_effect : true

#%questscrolls_Task%变量的默认值 ( 玩家无进行中的任务时 )
variable : "&7暂无"

#玩家完成一条任务播放什么
sound_on_complete : "ENTITY_VILLAGER_YES"

#玩家完成所有任务播放什么
sound_on_complete_all : "ENTITY_VILLAGER_YES"

on_Cumulative : true
#是否开启累计奖励 ( 就算关闭也不会影响插件累计玩家的完成次数 )

Cumulative:
  - 1:
      - "say hello"
      - "say hello"
      - "say hello"
  - 5:
      - "say hello"
      - "say hello"
      - "say hello"
  - 10:
      - "say hello"
      - "say hello"
      - "say hello"
  - 20:
      - "say hello"
      - "say hello"
      - "say hello"
  - 50:
      - "say hello"
      - "say hello"
      - "say hello"
#键 是次数
#下面是执行对应的奖励
#同样 没有内置礼包系统 ( 麻烦又没人用,干脆配合礼包插件用挺好的 )