name: questscrolls
main: com.king.Zhu
version: 1.0

softdepend:
  - PlaceholderAPI

commands:
  questscrolls:
    description: This is a demo command.
    usage: /questscrolls
    permission: <plugin name>.set
    permission-message: You need to <permission>

permissions:
  questscrolls.set:
    description: administrator
    default: op